# Form implementation generated from reading ui file 'CalendarDemo.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(733, 515)
        Form.setStyleSheet("  /*Tool button styles */\n"
"QCalendarWidget QToolButton {\n"
"\n"
"height:40px;\n"
"width:150px;\n"
"color:white;\n"
"font-size:20px;\n"
"icon-size:56px,56px;\n"
"background-color:black;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"  /* header row */\n"
"QCalendarWidget  QWidget{\n"
"\n"
"alternate-background-color:rgb(128,128,128)\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"  /*normal days */\n"
"QCalendarWidget QAbstractItemView:enabled {\n"
"\n"
"\n"
"font-size:18px;\n"
"color:rgb(180,180,180);\n"
"background-color:black;\n"
"selection-background-color:rgb(64,64,64);\n"
"selection-color:rgb(0,255,0);\n"
"\n"
"\n"
"\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.calendarWidget = QtWidgets.QCalendarWidget(Form)
        self.calendarWidget.setObjectName("calendarWidget")
        self.horizontalLayout.addWidget(self.calendarWidget)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox = QtWidgets.QSpinBox(Form)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_2.addWidget(self.spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        #connect signal
        self.pushButton.clicked.connect(self.calculate)

        self.verticalLayout.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_reservation = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_reservation.setFont(font)
        self.label_reservation.setText("")
        self.label_reservation.setObjectName("label_reservation")
        self.verticalLayout.addWidget(self.label_reservation)
        self.label_result = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_result.setFont(font)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.verticalLayout.addWidget(self.label_result)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def calculate(self):
        roomRent = 40
        dateSelected = self.calendarWidget.selectedDate()
        dateInString = str(dateSelected.toPyDate())
        numDays = self.spinBox.value()

        self.label_reservation.setText("Date of Reservation {} , Number of Days {} ".format(dateInString, numDays) )
        total = roomRent * numDays
        self.label_result.setText("Room rent for single day {} , Total Amount {} ".format(roomRent, total))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Date of Reservation:"))
        self.label_2.setText(_translate("Form", "Number of Days:"))
        self.pushButton.setText(_translate("Form", "Calculate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
