# Form implementation generated from reading ui file 'CheckDemo.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(681, 466)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_pizza = QtWidgets.QCheckBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_pizza.setFont(font)
        self.checkBox_pizza.setObjectName("checkBox_pizza")

        #connect to signal
        self.checkBox_pizza.stateChanged.connect(self.check_selected)
        self.verticalLayout.addWidget(self.checkBox_pizza)
        self.checkBox_salad = QtWidgets.QCheckBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_salad.setFont(font)
        self.checkBox_salad.setObjectName("checkBox_salad")

        # connect to signal
        self.checkBox_salad.stateChanged.connect(self.check_selected)
        self.verticalLayout.addWidget(self.checkBox_salad)
        self.checkBox_sausage = QtWidgets.QCheckBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_sausage.setFont(font)
        self.checkBox_sausage.setObjectName("checkBox_sausage")

        # connect to signal
        self.checkBox_sausage.stateChanged.connect(self.check_selected)
        self.verticalLayout.addWidget(self.checkBox_sausage)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label_result = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_result.setFont(font)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.verticalLayout_2.addWidget(self.label_result)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)


    def check_selected(self):
        price = 10

        if self.checkBox_pizza.isChecked():
            price = price + 3

        if self.checkBox_salad.isChecked():
            price = price + 4

        if self.checkBox_sausage.isChecked():
            price = price + 5

        self.label_result.setText("Total Price Is : {} ".format(price))

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Regular Tuna Price: 10"))
        self.label_2.setText(_translate("Dialog", "Select More:"))
        self.checkBox_pizza.setText(_translate("Dialog", "Pizza: 3"))
        self.checkBox_salad.setText(_translate("Dialog", "Salad: 4"))
        self.checkBox_sausage.setText(_translate("Dialog", "Sausage: 5"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
