# Form implementation generated from reading ui file 'SpinBoxDemo.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 250)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_price = QtWidgets.QLineEdit(Form)
        self.lineEdit_price.setObjectName("lineEdit_price")
        self.horizontalLayout.addWidget(self.lineEdit_price)
        self.spinBox = QtWidgets.QSpinBox(Form)

        #connecting to signal
        self.spinBox.editingFinished.connect(self.first_result)

        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.lineEdit_totalPrice = QtWidgets.QLineEdit(Form)
        self.lineEdit_totalPrice.setObjectName("lineEdit_totalPrice")
        self.horizontalLayout.addWidget(self.lineEdit_totalPrice)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_Sprice = QtWidgets.QLineEdit(Form)
        self.lineEdit_Sprice.setObjectName("lineEdit_Sprice")
        self.horizontalLayout_2.addWidget(self.lineEdit_Sprice)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(Form)

        # connecting to signal
        self.doubleSpinBox.editingFinished.connect(self.second_result)

        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox)
        self.lineEdit_Tsugar = QtWidgets.QLineEdit(Form)
        self.lineEdit_Tsugar.setObjectName("lineEdit_Tsugar")
        self.horizontalLayout_2.addWidget(self.lineEdit_Tsugar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_result = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_result.setFont(font)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.verticalLayout.addWidget(self.label_result)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def first_result(self):
        penPrice = int(self.lineEdit_price.text())
        totalPenPrice = self.spinBox.value() * penPrice
        self.lineEdit_totalPrice.setText(str(totalPenPrice))

    def second_result(self):
        sugarPrice = int(self.lineEdit_Sprice.text())
        totalSugarPrice = self.doubleSpinBox.value() * sugarPrice
        self.lineEdit_Tsugar.setText(str(totalSugarPrice))

        totalPenPrice = int(self.lineEdit_totalPrice.text())

        totalAmount = totalPenPrice + totalSugarPrice

        self.label_result.setText("Total Price Is : {} ".format(totalAmount))





    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Pen Price:"))
        self.label_2.setText(_translate("Form", "Sugar Price:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
